[build]
  # Install Composer and Node.js dependencies, build assets, and optimize Laravel config
  command = "composer install --optimize-autoloader --no-dev && npm install && npm run prod && php artisan config:cache"
  publish = "public"

# Define environment variables (optional)
[build.environment]
  GO_VERSION = "1.19"  # If you are using Go, specify the required version
  NODE_VERSION = "16"  # Set the Node.js version (adjust as needed)
